site_name: FX Trading 101
site_url: https://gustavodomenico.github.io/
docs_dir: '../../docs/pt/'                           
site_dir: '../../../pt'    

theme:
  name: material
  language: pt
  include_homepage_in_sidebar: false
  features:
    - navigation.expand
nav:
  - Introdução: 
    - Definição: introduction/index.md   
    - Ingressos e Remessas: introduction/currency-flow.md
  - Mercado de Câmbio:
    - Negociação: fx-market/negotiation.md
    - Banco Central do Brasil: fx-market/central-bank.md
    - Estrutura do Mercado: fx-market/market-structure.md
    - Tipos e Modalidades: fx-market/fx-types.md
    - Papel do Banco Central: fx-market/central-bank.md
  - Risco Cambial:
    - Fundamentos: risk/fundamentals.md
    - Derivativos para Hedge Cambial: risk/hedging.md
    - Tesouraria corporativa: risk/corporate-treasury.md
    - Transferência de Risco: risk/risk-transfer.md
  - Casos de uso: use-cases.md

extra:
  alternate:
    - name: Portuguese
      link: https://gustavodomenico.github.io/pt/
      lang: pt
    - name: English
      link: https://gustavodomenico.github.io/en/
      lang: en
extra_css:
  - css/custom.css